/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./global.css"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background) / <alpha-value>)",
        backgroundAlt: "rgb(var(--background-alt) / <alpha-value>)",
        surface: "rgb(var(--surface) / <alpha-value>)",
        surfaceAlt: "rgb(var(--surface-alt) / <alpha-value>)",
        surfaceElevated: "rgb(var(--surface-elevated) / <alpha-value>)",
        surfaceInverse: "rgb(var(--surface-inverse) / <alpha-value>)",
        overlay: "rgb(var(--overlay) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
        borderStrong: "rgb(var(--border-strong) / <alpha-value>)",
        text: "rgb(var(--text) / <alpha-value>)",
        textMuted: "rgb(var(--text-muted) / <alpha-value>)",
        textInverse: "rgb(var(--text-inverse) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        primaryHover: "rgb(var(--primary-hover) / <alpha-value>)",
        primaryPressed: "rgb(var(--primary-pressed) / <alpha-value>)",
        primaryForeground: "rgb(var(--primary-foreground) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        secondaryHover: "rgb(var(--secondary-hover) / <alpha-value>)",
        secondaryPressed: "rgb(var(--secondary-pressed) / <alpha-value>)",
        secondaryForeground: "rgb(var(--secondary-foreground) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        infoForeground: "rgb(var(--info-foreground) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
        successForeground: "rgb(var(--success-foreground) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        warningForeground: "rgb(var(--warning-foreground) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        dangerHover: "rgb(var(--danger-hover) / <alpha-value>)",
        dangerPressed: "rgb(var(--danger-pressed) / <alpha-value>)",
        dangerForeground: "rgb(var(--danger-foreground) / <alpha-value>)",
        disabled: "rgb(var(--disabled) / <alpha-value>)",
        disabledForeground: "rgb(var(--disabled-foreground) / <alpha-value>)",
        focus: "rgb(var(--focus) / <alpha-value>)",
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
        "4xl": "40px",
        "5xl": "48px",
        "6xl": "64px",
      },
      borderRadius: {
        control: "14px",
        card: "20px",
        panel: "24px",
        pill: "9999px",
        cell: "12px",
      },
      boxShadow: {
        soft: "0 1px 2px rgba(15, 23, 42, 0.06)",
        card: "0 12px 30px rgba(15, 23, 42, 0.08)",
        lift: "0 20px 40px rgba(15, 23, 42, 0.14)",
      },
      fontSize: {
        headlineLg: [
          "2.25rem",
          {
            lineHeight: "2.625rem",
            fontWeight: "700",
            letterSpacing: "-0.045rem",
          },
        ],
        headlineMd: [
          "1.875rem",
          {
            lineHeight: "2.25rem",
            fontWeight: "700",
            letterSpacing: "-0.028rem",
          },
        ],
        titleLg: [
          "1.375rem",
          {
            lineHeight: "1.875rem",
            fontWeight: "700",
            letterSpacing: "-0.014rem",
          },
        ],
        titleMd: [
          "1.125rem",
          {
            lineHeight: "1.625rem",
            fontWeight: "600",
            letterSpacing: "-0.01em",
          },
        ],
        bodyLg: ["1.125rem", { lineHeight: "1.75rem" }],
        bodyMd: ["1rem", { lineHeight: "1.5rem" }],
        bodySm: ["0.875rem", { lineHeight: "1.375rem" }],
        labelMd: [
          "0.875rem",
          { lineHeight: "1.25rem", fontWeight: "600", letterSpacing: "0.01em" },
        ],
        labelSm: [
          "0.75rem",
          { lineHeight: "1rem", fontWeight: "600", letterSpacing: "0.01em" },
        ],
        overline: [
          "0.7rem",
          { lineHeight: "1rem", letterSpacing: "0.18em", fontWeight: "700" },
        ],
        caption: ["0.8125rem", { lineHeight: "1.125rem" }],
        footnote: ["0.75rem", { lineHeight: "1rem" }],
      },
    },
  },
  plugins: [],
};
